name: Bug report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what you tried to do and what the bug is.
    validations:
      required: true

  - type: textarea
    id: excepted
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: dropdown
    id: system
    attributes:
      label: Operating system
      description: |
        What operating system(s) are you experiencing the problem on?
      multiple: true
      options:
        - GNU/Linux (describe below)
        - Windows 11
        - Windows 10
        - Windows 7
        - macOS 12 (Monterey)
        - macOS 11 (Big Sur)
        - macOS 10.15 (Catalina)
        - macOS 10.14 (Mojave)
        - macOS 10.13 (High Sierra)
        - macOS 13 (Ventura)
        - Windows 8.1
        - Windows 8
        - Isn't in the list (describe below)
    validations:
        required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra details about your system
      description: |
        If you're on a *nix system, please describe your distro and desktop environment
    validations:
      required: false
